

name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 5133f50f309707ae2e6b229bc95adcc907f8a7d9

    - name: Build C Code
      run: |
        git submodule update --init
        autoreconf -i
        ./configure
        make
