

name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 5133f50f309707ae2e6b229bc95adcc907f8a7d9
    - name: Install deps
      run: |
        sudo apt update
        sudo apt install  libxkbcommon-dev  
        sudo apt install libglib2.0-dev libgio2.0-cil-dev libglib2.0-0

    - name: Build C Code
      run: |
        git submodule update --init
        autoreconf -i
        ./configure --prefix=/usr
        make
