

name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 5133f50f309707ae2e6b229bc95adcc907f8a7d9
    - name: Install deps
      run: |
        sudo apt update
        sudo apt install wget
        sudo apt install  libxkbcommon-dev  
        sudo apt install libglib2.0-dev libgio2.0-cil-dev libglib2.0-0
        sudo apt install libxcb-ewmh-dev libxcb-icccm4-dev libxcb-xkb-dev libxkbcommon-x11-dev libxcb-cursor-dev libxcb-randr0-dev libxcb-xinerama0-dev
        sudo apt-get install libglib2.0-dev libxcb1-dev libxcb-util-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-cursor-dev libxcb-randr0-dev libxcb-xinerama0-dev
        sudo apt-get install libpango1.0-dev libpangocairo-1.0-0
        sudo apt-get install libstartup-notification0-dev
        sudo apt-get install check
    - name: download tar and extract it
      run: | 
        git submodule update --init
        autoreconf -i
        mkdir build
        cd build
        ../configure
        make

